version: '3'

name: inception
services:
  mariadb:
    container_name: mariadb
    image: nibenoit/mariadb
    build: 
      context: requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWD
        - MYSQL_USER
        - MYSQL_USER_PASSWD
        - MYSQL_DATABASE
    networks:
      - inception
    restart: always
    environment:
      - MYSQL_ROOT_PASSWD
      - MYSQL_USER
      - MYSQL_USER_PASSWD
      - MYSQL_DATABASE
    volumes:
      - mariadb:/var/lib/mysql
  wordpress:
    container_name: wordpress
    image: nibenoit/wordpress
    build: requirements/wordpress
    networks:
      - inception
    restart: always
    environment:
      - MYSQL_USER
      - MYSQL_USER_PASSWD
      - MYSQL_DATABASE
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb
  nginx:
    container_name: nginx
    image: nibenoit/nginx
    build:
      context: requirements/nginx
      args:
        - NGINX_DOMAIN
    networks:
      - inception
    restart: always
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress

volumes:
  mariadb:
    name: mariadb
    driver: local
  wordpress:
    name: wordpress
    driver: local

networks:
  inception:
    driver: bridge