version: '3.9'

services:
  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWD
    networks:
      - inception
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWD
    volumes:
      - mariadb:/var/lib/mysql
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    networks:
      - inception
    restart: unless-stopped
    environment:
      - MYSQL_USER
      - MYSQL_PASSWD
      - MYSQL_DATABASE
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      args:
        - NGINX_DOMAIN
    networks:
      - inception
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/mariadb
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/wordpress

networks:
  inception:
    driver: bridge