version: '3.9'

name: inception
services:
  mariadb:
    container_name: mariadb
    image: apigeon/mariadb
    build: 
      context: requirements/mariadb
    environment:
      - MYSQL_ROOT_PASSWD
      - MYSQL_USER
      - MYSQL_USER_PASSWD
      - MYSQL_DATABASE
      - MYSQL_GITEA_USER
      - MYSQL_GITEA_PASSWD
      - MYSQL_GITEA_DATABASE
    networks:
      - inception
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql